import type { StrategyNode, StrategyEdge } from '../types';

export const INITIAL_NODES: StrategyNode[] = [
  {
    id: 'shift_core',
    type: 'strategyNode',
    position: { x: 80, y: 240 },
    data: {
      title: 'СДВИГ БИЗНЕС-МОДЕЛИ ДЕЙТИНГА',
      badge: 'Paradigm Shift',
      category: 'foundation',
      description: 'Смещение фокуса оплаты: пользователь платит НЕ за поиск пары и дейтинг, а за комьюнити, статус, доступ к закрытому сообществу и мероприятиям.',
      keyMetric: 'Цель — Top-1 Retention среди мобильных приложений.',
      tags: ['Strategy', 'Disruption', 'Foundation'],
      notes: 'Ключевая смена парадигмы: отказ от модели "оплаты за обещание любви" к модели "членства в желанном закрытом клубе".',
    },
  },
  {
    id: 'emotion_status',
    type: 'strategyNode',
    position: { x: 500, y: 240 },
    data: {
      title: 'ЗА ЧТО ПЛАТИТ КЛИЕНТ',
      badge: 'Value Delivery',
      category: 'psychology',
      description: '• 1-я очередь: Чистые эмоции.\n• 2-я очередь: Статус, социальная значимость, нетворкинг, пафос и понт от факта использования.',
      tags: ['Psychology', 'Status', 'Emotions'],
      notes: 'Люди покупают не функции, а эмоциональные состояния и социальные доказательства своей ценности.',
    },
  },
  {
    id: 'hardware_beacon',
    type: 'strategyNode',
    position: { x: 940, y: 60 },
    data: {
      title: 'HARDWARE: СОЦИАЛЬНЫЙ СИГНАЛИЗАТОР',
      badge: 'Retention Tool',
      category: 'hardware',
      description: 'Физический маркер («сигналка на башке/теле»), который носится открыто. Обязательное условие: высокая узнаваемость бренда.',
      outcome: 'Удовлетворяет базовое желание выделиться → рождает эмоцию отличности («не такой / не такая», эксклюзивность).',
      tags: ['Hardware', 'Signaling', 'Exclusivity'],
      notes: 'Служит визуальным маяком принадлежности к касте избранных в физическом мире.',
    },
  },
  {
    id: 'gym_model',
    type: 'strategyNode',
    position: { x: 940, y: 440 },
    data: {
      title: 'МЕХАНИКА СПОРТЗАЛА',
      badge: 'Habit Loop',
      category: 'retention',
      description: 'Офлайн-события — главный канал доставки эмоций. Модель подписки как в спортзал: сформирована эмоциональная привязка к мероприятиям, человек чувствует, что он должен на них ходить.',
      tags: ['Retention', 'Gym-Model', 'Offline-First'],
      notes: 'Покупка абонемента создает психологический триггер "не пропустить оплаченное", превращаясь в ритуал.',
    },
  },
  {
    id: 'event_duality',
    type: 'strategyNode',
    position: { x: 1400, y: 240 },
    data: {
      title: 'ДВОЙСТВЕННОСТЬ МЕРОПРИЯТИЙ',
      badge: 'Execution',
      category: 'event',
      description: '• Снаружи: Публичная масштабность (для накачки узнаваемости бренда и «сигналки»).\n• Внутри: Физическая камерность (сохранение приватности, ценности и элитарности).',
      tags: ['Events', 'Duality', 'Brand Power'],
      notes: 'Внешний хайп привлекает внимание масс; внутренняя приватность удерживает ключевое ядро аудитории.',
    },
  },
  {
    id: 'anti_churn',
    type: 'strategyNode',
    position: { x: 1840, y: 240 },
    data: {
      title: 'СИСТЕМА ОБНОВЛЕНИЙ (ANTI-CHURN)',
      badge: 'Relevance Engine',
      category: 'lifecycle',
      description: 'Продукт никогда не теряет моду благодаря двухуровневым обновлениям:\n• Приоритет №1: Обновления на физическом уровне (Hardware).\n• Приоритет №2: Ротация форматов и масштабов мероприятий.',
      tags: ['Anti-Churn', 'Hardware V2', 'Innovation'],
      notes: 'Двойная система апгрейдов устраняет сенсорную адаптацию и затухание интереса.',
    },
  },
  {
    id: 'goal_retention',
    type: 'strategyNode',
    position: { x: 2280, y: 240 },
    data: {
      title: 'ТОП-1 RETENTION В СТОРАХ',
      badge: 'End Result',
      category: 'outcome',
      description: 'Высочайший LTV и L-curve retention: люди не удаляют приложение после нахождения пары, так как состоят в постоянном клубе.',
      keyMetric: 'Рекордный LTV в индустрии мобильных приложений.',
      tags: ['Outcome', 'Top-1 Retention', 'LTV'],
      notes: 'Преодоление проклятия дейтинга: нахождение партнера больше не является точкой оттока (churn event).',
    },
  },
];

export const INITIAL_EDGES: StrategyEdge[] = [
  {
    id: 'e_shift_emotion',
    source: 'shift_core',
    target: 'emotion_status',
    type: 'customEdge',
    animated: true,
    data: {
      label: 'смещает ценность в',
      styleType: 'bezier',
      color: '#00F0FF',
    },
  },
  {
    id: 'e_emotion_hardware',
    source: 'emotion_status',
    target: 'hardware_beacon',
    type: 'customEdge',
    animated: true,
    data: {
      label: 'материализуется через',
      styleType: 'bezier',
      color: '#F59E0B',
    },
  },
  {
    id: 'e_emotion_gym',
    source: 'emotion_status',
    target: 'gym_model',
    type: 'customEdge',
    animated: true,
    data: {
      label: 'доставляется через',
      styleType: 'bezier',
      color: '#10B981',
    },
  },
  {
    id: 'e_hardware_event',
    source: 'hardware_beacon',
    target: 'event_duality',
    type: 'customEdge',
    animated: true,
    data: {
      label: 'подпитывает снаружи',
      styleType: 'bezier',
      color: '#3B82F6',
    },
  },
  {
    id: 'e_gym_event',
    source: 'gym_model',
    target: 'event_duality',
    type: 'customEdge',
    animated: true,
    data: {
      label: 'базируется на структуре',
      styleType: 'bezier',
      color: '#3B82F6',
    },
  },
  {
    id: 'e_hardware_antichurn',
    source: 'hardware_beacon',
    target: 'anti_churn',
    type: 'customEdge',
    animated: true,
    data: {
      label: 'требует циклов',
      styleType: 'bezier',
      color: '#F43F5E',
    },
  },
  {
    id: 'e_event_antichurn',
    source: 'event_duality',
    target: 'anti_churn',
    type: 'customEdge',
    animated: true,
    data: {
      label: 'обновляется через',
      styleType: 'bezier',
      color: '#F43F5E',
    },
  },
  {
    id: 'e_antichurn_retention',
    source: 'anti_churn',
    target: 'goal_retention',
    type: 'customEdge',
    animated: true,
    data: {
      label: 'гарантирует бесконечный LTV',
      styleType: 'bezier',
      color: '#EAB308',
    },
  },
];
